# User config
author: "Dawon Ko"
tagline: "Dawon Ko Homepage"
description: "Hi! I am Dawon, interested in everything related to Marketing - campains, research, product. London based.🙋 "
keywords: "Dawon, Marketing, Portfolio"
email: "dawonkouk@gmail.com"
linkedin: "https://www.linkedin.com/in/dawon-ko"
twitter: "https://twitter.com/"
github: "https://github.com/dawonko/Python-study"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

#analytics

analytics:
  provider: google
  google:
    tracking_id : G-2GP5LKVRQX
