# User config
author: "Dawon Ko"
tagline: "Pineapple Certfied Jekyll Theme"
description: "Hi! I am Dawon, interested in everything related to Marketing - campains, research, product development."
keywords: "Dawon, Marketing, Portfolio"
email: "dawonkouk@gmail.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
